### PR TITLE
Add O_RSYNC + fallocate on solarish, and fadvise on illumos

### PR DESCRIPTION
**Pull request by sunshowers**
These functions were added to libc 0.2.161, and are required by some downstream crates.

### CODE REVIEW

**Comment by sunshowers** [comment]
(Once this lands I'd also love a pick onto the 0.38 branch -- happy to do it myself.)

**Comment by sunfishcode** [comment]
Thanks!

**Comment by sunfishcode** [comment]
I've now posted https://github.com/bytecodealliance/rustix/pull/1192 to backport this to the 0.38 branch.

**Comment by sunshowers** [comment]
Thank you!

**Pull request merged**
