### PR TITLE
Make termios constants support AIX

### PR DESCRIPTION
**Pull request by ecnelises**
Mark those related constants as unsupported on AIX.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Thanks! I know those `cfg`s are really tricky to get right. I think this is a case where having src/termios/mod.rs use `use constants::*` and having constants.rs do `use backend::termios::types::*` would significantly simplify this. I'll do this hopefully soon, but alternatively feel free to make this change yourself if you'd like.

**Comment by ecnelises** [comment]
I posted https://github.com/bytecodealliance/rustix/pull/543

**Comment by sunfishcode** [comment]
#543 is now merged, so this PR can now be simplified accordingly :-).

**Comment by sunfishcode** [comment]
I took the liberty of resolving the merge conflicts here.

**Comment by ecnelises** [comment]
Thanks!

**Pull request merged**
