### PR TITLE
Add GNU/Hurd support

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by sunfishcode** [comment]
Thanks! This looks good; could you also add a `cargo check -Z build-std --target=i686-unknown-hurd-gnu --features=all-apis` line to the "Check selected Tier 3 platforms" section in .github/workflows/main.yml script, so that we avoid breaking GNU/Hurd support in the future?

**Comment by sthibaul** [comment]
Yes, that'll just have to wait for https://github.com/rust-lang/libc/pull/3325 to land

**Comment by sunfishcode** [comment]
Ah, I didn't realize we were at that early stage of the process. My sense then is that we can merge this now, and add the CI check later once it's ready.

**Comment by sthibaul** [comment]
Thanks, I have created the backport PR https://github.com/bytecodealliance/rustix/pull/852 for rustc bootstrap

**Comment by sunfishcode** [comment]
This is now released in rustix 0.38.15.

**Comment by sthibaul** [comment]
Thanks!

**Pull request merged**
