### PR TITLE
Add mount syscall

### LINKED ISSUE #491: Add mount syscall?
It'd be nice to have. Nix version: https://docs.rs/nix/latest/nix/mount/index.html

### PR DESCRIPTION
**Pull request by SUPERCILEX**
My flag management is absolutely terrible, any suggestions would be appreciated. :) The goal is to try and only provide applicable flags (which is maybe a hopeless cause), but that means having partially overlapping sets thereby complicating everything. Also, `StatVfsMountFlags` are related, not sure if we should somehow combine things.

In another PR, I'll add umount.

Closes #491

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Cool beans, as long as we agree on the API surface we can muck around with the flags later if they become an issue.

**Comment by SUPERCILEX** [comment]
Every nightly check is currently broken because of a missing fuschia build.

**Comment by sunfishcode** [comment]
The fuchsia fix is now on main, so rebasing on main should fix the CI here. I also don't have time today to review this, but at a superficial glance this looks good.

**Comment by SUPERCILEX** [comment]
Yeep, fixed.

**Comment by sunfishcode** [comment]
Looks good, thanks!

**Comment by SUPERCILEX** [comment]
Woohoo! Unmount: https://github.com/bytecodealliance/rustix/pull/512

**Pull request merged**
