### PR TITLE
Update windows-sys to 0.42.0

### PR DESCRIPTION
**Pull request by messense**
* https://github.com/microsoft/windows-rs/releases/tag/0.42.0
* https://github.com/sunfishcode/io-lifetimes/pull/46

### CODE REVIEW

**Comment by sunfishcode** [comment]
Thanks!

**Comment by nox** [comment]
@sunfishcode Could we get a new release which includes this change please? 🥺

**Comment by sunfishcode** [comment]
Sure! #437 is a backport to the release branch; once that lands, I'll do a release.

**Comment by sunfishcode** [comment]
0.35.13 is now up, with this change!

**Pull request merged**
