### PR TITLE
Fix new warnings on nightly

### PR DESCRIPTION
**Pull request by notgull**
static mut is now discouraged; however it appears that the places we use static mut can be removed pretty easily.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Thanks! Could you also remove the "SAFETY:" labels in the comments that no longer precede `unsafe` blocks?

**Comment by notgull** [comment]
> Could you also remove the "SAFETY:" labels in the comments that no longer precede `unsafe` blocks?

These still involve loading pointers to raw functions/weird memory regions, so I figured they should remain.

**Comment by sunfishcode** [comment]
The contents of the comments can stay. But if Rust doesn't consider the code `unsafe` then these aren't "SAFETY" comments per se.

**Comment by notgull** [comment]
> The contents of the comments can stay. But if Rust doesn't consider the code `unsafe` then these aren't "SAFETY" comments per se.

Ok, this has been updated.

**Comment by sunfishcode** [comment]
Thanks!

**Pull request merged**
