### PR TITLE
Add GNU/Hurd support

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by sthibaul** [comment]
This is a backport of https://github.com/bytecodealliance/rustix/pull/844, needed for rustc bootstrap

**Comment by sunfishcode** [comment]
The CI is failing due to changes in the MIPS target in Rust. This was fixed on main in #793, so I've now opened https://github.com/bytecodealliance/rustix/pull/857 to backport that change to the 0.37 branch.

**Comment by sunfishcode** [comment]
@sthibaul #793 has now landed, and the 0.37 branch now passes its CI. Would you mind rebasing this PR on the latest 0.37 branch?

**Comment by sthibaul** [comment]
done so!

**Comment by sunfishcode** [comment]
Thanks!

**Comment by sunfishcode** [comment]
This is now released in 0.37.24.

**Pull request merged**
