### PR TITLE
Match casting type to the destination iov_len's type. fix #324

### LINKED ISSUE #324: `as u64` when left hand side of assignment can be 32 bit
Cant `iov_len` be `u32`?
https://github.com/bytecodealliance/rustix/blob/23841ae92b5d1ef772bb9a91dff067f67e5ec070/src/imp/linux_raw/io/io_slice.rs#L26

### PR DESCRIPTION
**Pull request by AsafFisher**
fix #326

### CODE REVIEW

**Comment by sunfishcode** [comment]
The patch looks good; it looks like the CI failure is something related to the latest nightly Rust. Locally, rustup only pulls in 2022-05-11, and the patch compiles, but the CI is somehow getting 2022-05-12. We can either temporarily pin to an older nightly, or just wait until newer nightlies are available to see if they fix this.

**Comment by sunfishcode** [comment]
The patch looks good; it looks like the CI failure is something related to the latest nightly Rust. Locally, rustup only pulls in 2022-05-11, and the patch compiles, but the CI is somehow getting 2022-05-12. We can either temporarily pin to an older nightly, or just wait until newer nightlies are available to see if they fix this.

**Comment by AsafFisher** [comment]
Merge?

**Comment by sunfishcode** [comment]
Yep, the issue seems to have been in the nightly build, which seems to be fixed now.

**Pull request merged**
