### PR TITLE
Support processing ancillary outside rustix infrastructure

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Specifically, I'm trying to parse control data from io_uring responses.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Test failures appear unrelated.

**Comment by notgull** [comment]
We had this error on `softbuffer` as well, it can be fixed by pinning `half` to v2.2.1

**Comment by SUPERCILEX** [comment]
@sunfishcode I don't think this requires a semver bump, right? I'm only changing private APIs and adding one new one.

**Comment by sunfishcode** [comment]
It looks like the change to `AncillaryDrain` to combine `read` and `length` into `read_and_lenghth` would be a semver bump.

**Comment by SUPERCILEX** [comment]
Hmmm, maybe I'm missing something, but all of those fields are private.

**Comment by sunfishcode** [comment]
Oh wow you're totally right.

**Review by sunfishcode — COMMENTED** [review]
Looks good. Two observations:

Looking at it now, it looks like a mistake to have `AncillaryDrain` hold `read` and `length` members. Rust standard library things like `Vec::drain` remove their elements even if the iterator is dropped without being iterated, so we should ideally do the same, and if we did, that would also eliminate this `Option`. However, we can do that in the next semver bump, because it is a subtle behavior change.

In general, it's a goal of `rustix` to provide safe APIs wherever possible, so this unsafe `parse` function is unforuntate, however a safe RecvMsg API for io_uring would be non-trivial, and possibly the best way thing to do within rustix is to just expose the unsafe primitives and look to higher-level crates to provide the safe abstractions on top of them.

**Pull request merged**
